name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # OMG THIS TEST IS DISABLED, PLZ MAKE TINYGRAD TINY AGAIN
  lines:
    name: Less than 1000 lines
    runs-on: ubuntu-latest
    if: ${{ false }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install SLOCCount
      run: sudo apt-get install sloccount
    - name: Check <1000 lines
      run: sloccount tinygrad test examples extra; if [ $(sloccount tinygrad | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 1000 ]; then exit 1; fi

  testmetal:
    name: Metal Tests
    runs-on: macos-13
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install -e '.[metal,testing]'
    #- name: Run dtype test
    #  run: DEBUG=4 METAL=1 python -m pytest test/test_dtype.py
    - name: Run ops test
      run: DEBUG=4 METAL=1 python -m pytest test/test_ops.py
    # dtype test has issues on test_half_to_int8

  # disabled, this test is flaky
  testdocker:
    name: Docker Test
    runs-on: ubuntu-latest
    if: ${{ false }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build Docker
      run: docker build -t tinygrad -f test/Dockerfile .
    - name: Test Docker
      run: docker run --rm tinygrad /usr/bin/env python3 -c "from tinygrad.tensor import Tensor; print(Tensor.eye(3).numpy())"
